<a href="https://colab.research.google.com/github/YakovDeLeon/ML_Course_PT/blob/main/Hometasks/PT_HT3_WhoIsTalking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание 3

В этом задании мы предлагаем вам не только улучшить [бейзлайн, который мы дали вам на занятии](https://colab.research.google.com/drive/1DirkE2idWXfl7TqTF0ZxBi6M37LZ0NGD?usp=sharing), но и продумать задание с точки зрения ML System Design. Ответы на вопросы, которые мы поставим перед вами, могут повлиять на код (метрики, модели и так далее).

Вам предстоит спроектировать систему классификации TCP-потоков по приложению/сервису на основе усечённой последовательности длин пакетов (до 30 значений, с направлением).

Представьте, что вы не просто обучаете модель, а проектируете промышленное решение, которое будет использоваться в корпоративной среде.

### Важно!

Сначала почитайте и изучите ноутбук и код с занятия.

# 1. Бизнес-контекст и целеполагание

Вопрос:
Зачем и кому может быть нужна система классификации приложений по зашифрованному трафику? Как и где она будет использоваться?

В ответе опишите:

- Кто является заказчиком (SOC-команда, отдел ИБ, провайдер, корпорация, государственная структура и т.д.)?

-  Какие реальные бизнес-задачи она решает?

- В каком режиме работает система:

офлайн-анализ (батч),

near-real-time,

real-time (inline)?

- Какие требования к:

задержке (latency),

пропускной способности,

интерпретируемости,

объяснимости,

обновляемости модели?

- Какие риски есть при ошибках классификации (FP/FN)?

# Ответ

Классификация приложений по зашифрованному трафику нужна в первую очередь для систем съёма трафика, в которых необходимо определить какие сервисы посещает пользователь и ограничивать доступ к нежелательному контенту со стороны системного администратора и блокировать различные кибер угрозы. Системы съёма трафика могут быть как активными, так и пассивными. Активные системы, например файрволл, встраиваются по середине между отправителем и получателем и могут модфифицировать оригинальные пакеты и блокировать трафик в момент его прихода, поэтому относятся к системам жёсткого реального времени. При пассивном съёме, например DPI, в систему попадает копия уже запроксированного трафика. Такие системы используются в основном для анализа трафика и выявления в нём различных аномалий. Так как в такую систему попадает уже копия трафика требования к задержкам тут ниже, но всё же хотелось выявить атаку как можно быстрее. Поэтому такие системы относятся к системам мягкого реального времени.

Для определённости, в рамках текущей задачи попытаемся встроить классификацию приложений в зашифрованном траффике в файрвол. Файрвол обычно поддерживает MITM и умеет дешифровать трафик, однако весь трафик обычно не дешифруются, так как это требует огромных вычислительных ресурсов, поэтому через файрвол TLS идёт в соотношении: 30% - расшифровывается, 70% - нет. Зашифрованный трафик файрвол уже умеет классифицировать по SNI, который передаётся при установлении соединения. Однако злоумышленник может использовать фейковый SNI и тем самым обходить политики безопасности.

Исходя из этого требования к модели следующие:
* Анализ в режиме real-time, любые задержки могут быть критичные для пользователя
* Latency: Модель должна принимать решение не позднее чем через 4кб для каждой из сторон, или суммарно 8 кб.
* В иделае модель должна быть легковесной и не должна влиять на пропускную способность, как будет на практике сказать сложно, но не хотелось допустить сильную деградацию производительности
* Интерпретируемость: Решение модели должно быть трассируемым до набора входных признаков.
* Модель должна содержать информацию о принятом решении, чтобы SOC команда смогла отличить правильное решение модели от ложного срабатывания
* Модель должна обновляться ежедневно, чтобы оперативно реагировать на новые угрозы. Обновление модели не должно приводить к перезапуску NGFW и влиять на обработку DP данных
* При ложном срабатывании может блокироваться легитимный трафик, поэтому должна быть надстройка на СУ, позволяющая отключить учёт результата модели

# 2. Данные и обработка: классы, дисбаланс, новые сервисы

Вопрос:
- Как нужно подготовить данные и организовать работу с классами, учитывая сильный дисбаланс?

В ответе раскройте:

- Нужно ли:

агрегировать редкие классы в "Other"?

удалять самые редкие классы?


- Как дисбаланс повлияет на:

обучение,

переобучение,

выбор метрики,

интерпретацию результатов?


- Какие стратегии борьбы с дисбалансом вы бы применили?

- Как система должна реагировать на новые приложения, которых не было в обучающей выборке?

- Нужно ли учитывать изменение поведения сервисов со временем (concept drift)?

# Ответ:

Для ngfw 20% от известных приложений будет составлять примерно 80% всего трафика. На остальные 70% приложений придётся, проценты или доли процентов трафика и ещё 10% попадут под нулевые срабатывания.

Поэтому очень редкие классы будет уместно аггрегировать в какую-то более общую категорию. Те классы, которые не представляют угрозы и имеют мало примеров трафика имеет смысл объединить в "Unknown application". Классы, которые являются редкими, но критичными к безопасности (например VPN, TOR, C2) нужно сохранять.

Самые редкие классы имееть смысл удалять, если:
* класс является шумовым
* плохо размечен
* имеет слишком мало данных
* не является значимым для security

В идеале такие классы лучше агрегировать в один или переводить в "Unknown applications".

Посколько самые популярные классы всегда будут составлять большую долю трафика возникает дисбаланс. Поэтому при обучении важно вносить корректировки в модель, иначе модель:
* будет минимизировать общую ошибку
* будет игнорировать миноритарные классы

Пример:

YouTube — 60%
Slack — 20%
Zoom — 10%
VPN — 0.5%
TOR — 0.1%

Модель может полностью игнорировать TOR и всё равно иметь 99% accuracy.

При таком дисбалансе, существует большой риск, что миноритарные классы:
* легко переобучаются
* модель просто запоминает конкретные TLS-потоки
* плохая генерализация (плохая обобщающая способность)

При выборре метрики общая accuracy будет работать плохо, так как мы не будем видеть какие классы путаем между собой. Например ютуб будет угадываться всегда, VPN - нет, но accuracy будет высокий. Поэтому в этом случае лушче исопльзовать:
* матрицу предсказаний (precision, recall)
* f1-меру
* каждую из этих метрик смотрим по сработке на каждый конкретный класс

Для борбы с дисбалансом будем использовать взвешивание классов. Для более редких будем назначать более высокий способ. Самый простой способ в качестве веса взять 1 / частоту встречания (других пока не знаю:-)). Однако надо понимать, что на разных предприятих, где установлен NGFW, может быть разный трафик, поэтому здесь хорошо бы собрать данных с разных мест.

Чатгпт ещё предлагает попробовать иерархическую классификацию, но это может увеличить сложность вычислений и привести к большей деградации, поскольку несколько моделей надо запускать по несколько раз на одном и том же наборе данных. Это может быть особенно заметно, если мы захотим также гонять содержимое зашифрованного трафика (хотя пока сложно сказать, насколько в этом есть смысл). Точно сказать, как себя поведёт модель тут сложно, надо исследовать.

При появлении новых приложений, модель может относить их к уже известным классам, что может быть не очень хорошо, так как новые VPN будут классифицироваться например как YouTube. Поэтому для контроля для с этим чатгпт советует:
* Threshold по confidence. Если max probability < T → Unknown
* Energy-based detection
* Distance to class centroid
* One-class classifier поверх эмбеддингов

Моделью должен обязательно учитываться concept-drift. Так как большинство приложений используют в основном REST API поверх HTTP внутри TLS, то взаимодействие между клеинтом и сервером может меняться со времени из-за обновления протокола взаимодействия. Это может отразиться на разных размерах пакетов, на разных урлах внутри процедуры обмена сообщения, если в каждом регионе размещён свой сервер.

Исходя из этого drift может быть:
* Feature drift (изменились количество данных отправялемых клиентом и сервером за тот же промежуток наблюдения)
* Prior drift (изменилось распределение классов, например из-за замедления ютуба, в топ может вылезти рутуб)
* Label drift (класс изменил поведение, (сомнительно, но окэй, не придумал пример такого))

Что с этим делать:
* Continuous monitoring
  * Track per-class recall over time
  * Track feature distribution
* Периодическое переобучение
  * Раз в день/месяц
  * Или при детекте деградации
  * Но тут вопрос какие данны подавать для переобчения, вряд ли снимать весь трафик на терабайты и подавать его на переобучение будет хорошей идеей. Наверное тут правильнее будет отдавать трафик с данными, которые попали под категорию "Unknown Applictaion"

* Shadow validation
  * Новая модель проверяется параллельно старой.

# 3. Метрика и выбор алгоритмов

Вопрос:
Какую метрику качества вы выберете и почему? Нужно ли ограничивать себя определёнными алгоритмами?


- Выберите и обоснуйте метрику.

- Объясните, почему выбранная метрика соответствует бизнес-целям.

- Нужно ли использовать несколько метрик?

- Допустимы ли любые модели? Есть ли ограничения?

# Ответ

Как уже было сказано ранее, у нас имеется сильный дисбаланс классов, при этом NGFW должен не пропускать угрозы (то есть должен быть высокий recall) и не блокировать легитимный трафик (должен быть высокий precision). F1 является компроммисом между ними. Но для информативности будем использовать все три метрики:
* Для оценки безопасности, используем recall, так как среди всего трафика мы должны блокировать как можно больше того, что попадает под угрозы
* Для оценки стабильности используем Precision, чтобы понимать насколько можно доверять результату
* Для оценки общей устойчивости, будем использовать f-score

Модель не должна оказывать сильного влияния на обработку сетевого трафика. Поэтому ма должны ориентироваться на максимально лёгкие модели, например:
* Logistic Regression
* Gradient Boosted Trees (ограниченной глубины)

# 4. Персональные данные, приватность и деплой

Вопрос:
Считается ли такой датасет персональными данными? Какие риски существуют?


- Можно ли по последовательности размеров пакетов деанонимизировать пользователя?

- Где может быть развернута система:

on-premise,

в облаке,

на edge-устройствах?

- Какие меры нужно предусмотреть:

анонимизация,

логирование,

ограничение хранения,

контроль доступа?

# Ответ!

Да такой датасет является персональными данными. В худшем случае если соотнести размеры пакетов с трафиком, где они были они добыты, то можно узнать ip пользователя. По нему найти весь его трафик, а там если много вычислительных ресурсов можно и весь трафик попытаться дешифровать.

Система должна быть развёрнута on-permise. Для обучения модели трафик можно сгенерировать своими силами внутри компании, поэтому нет смысла выносить систему куда-то ещё.

Так как модель не покидает периметра компании, то кажется кроме контроля доступа здесь дополнительно ничего не треубется.

# Улучшение бейзлайна.

Наконец, вы можете писать код!

С учетом выбранной метрики и выбранного пула алгоритмов, улучшите бейзлайн с занятия:

- Поработайте с признаками - придумайте новые, затем попробуйте отбор признаков
- Поработайте с разными моделями, подбирайте у них гиперпараметры
- Можете попробовать использовать кластеризацию для извлечения дополнительных признаков

<a href="https://colab.research.google.com/github/YakovDeLeon/ML_Course_PT/blob/main/Lecture4_Clustering%26MLSD/PT_Practice4_WhoIsTalking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Сначала скачаем данные

In [1]:
!wget -O response.json \
"https://cloud-api.yandex.net/v1/disk/public/resources/download?public_key=https://disk.yandex.ru/d/7LCvNsGL1mv90Q"

--2026-03-04 08:37:00--  https://cloud-api.yandex.net/v1/disk/public/resources/download?public_key=https://disk.yandex.ru/d/7LCvNsGL1mv90Q
Resolving cloud-api.yandex.net (cloud-api.yandex.net)... 213.180.204.127, 2a02:6b8::1:127
Connecting to cloud-api.yandex.net (cloud-api.yandex.net)|213.180.204.127|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 617 [application/json]
Saving to: ‘response.json’

response.json       100%[===================>]     617  --.-KB/s    in 0s

2026-03-04 08:37:02 (36.8 MB/s) - ‘response.json’ saved [617/617]

In [2]:
import json

with open("response.json") as f:
    data = json.load(f)

print(data["href"])

https://downloader.disk.yandex.ru/disk/2cc0bb58fa52381e1088248dd2070aede68759a73fdeee494c05b7efd2022d65/69a8276e/fKqInKw3d7bLFOeFnMGnhOEt74e_AcHrfoeOiWQFqnxSx2KlJFe3moqi-rTFCO6djYu3q6EHAUP4X1BQu7yk7eyLDbl9lafVd4ruaDAPlxGr8npumZHI4midPdWhecNq?uid=0&filename=whos-talking-classify-the-app-by-its-packets.zip&disposition=attachment&hash=m8VLCd1u1YCGUik9dZVkJjbxXRNbrE0kS1p%2BEIBguw1klnm56L9GDaExZ6Yk0MeDq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=259847718&fsize=305374529&hid=11ebcd4213988e57481af625f75bf49e&media_type=compressed&tknv=v3

In [4]:
!wget -O archive.zip "https://downloader.disk.yandex.ru/disk/2cc0bb58fa52381e1088248dd2070aede68759a73fdeee494c05b7efd2022d65/69a8276e/fKqInKw3d7bLFOeFnMGnhOEt74e_AcHrfoeOiWQFqnxSx2KlJFe3moqi-rTFCO6djYu3q6EHAUP4X1BQu7yk7eyLDbl9lafVd4ruaDAPlxGr8npumZHI4midPdWhecNq?uid=0&filename=whos-talking-classify-the-app-by-its-packets.zip&disposition=attachment&hash=m8VLCd1u1YCGUik9dZVkJjbxXRNbrE0kS1p%2BEIBguw1klnm56L9GDaExZ6Yk0MeDq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=259847718&fsize=305374529&hid=11ebcd4213988e57481af625f75bf49e&media_type=compressed&tknv=v3"
# !wget -O archive.zip str(data["href"])

--2026-03-04 08:37:40--  https://downloader.disk.yandex.ru/disk/2cc0bb58fa52381e1088248dd2070aede68759a73fdeee494c05b7efd2022d65/69a8276e/fKqInKw3d7bLFOeFnMGnhOEt74e_AcHrfoeOiWQFqnxSx2KlJFe3moqi-rTFCO6djYu3q6EHAUP4X1BQu7yk7eyLDbl9lafVd4ruaDAPlxGr8npumZHI4midPdWhecNq?uid=0&filename=whos-talking-classify-the-app-by-its-packets.zip&disposition=attachment&hash=m8VLCd1u1YCGUik9dZVkJjbxXRNbrE0kS1p%2BEIBguw1klnm56L9GDaExZ6Yk0MeDq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=259847718&fsize=305374529&hid=11ebcd4213988e57481af625f75bf49e&media_type=compressed&tknv=v3
Resolving downloader.disk.yandex.ru (downloader.disk.yandex.ru)... 77.88.21.127, 2a02:6b8::2:127
Connecting to downloader.disk.yandex.ru (downloader.disk.yandex.ru)|77.88.21.127|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://s02klg.storage.yandex.net/rdisk/2cc0bb58fa52381e1088248dd2070aede68759a73fdeee494c05b7efd2022d65/69a8276e/fKqInKw3d7bLFOeFnMGnhOEt74e_AcHrfoeOiWQFqnxSx2KlJFe3moqi-rTFCO6djYu3q6EHAUP4X1BQu7yk7eyLDbl9lafVd4ruaDAPlxGr8npumZHI4midPdWhecNq?uid=0&filename=whos-talking-classify-the-app-by-its-packets.zip&disposition=attachment&hash=m8VLCd1u1YCGUik9dZVkJjbxXRNbrE0kS1p%2BEIBguw1klnm56L9GDaExZ6Yk0MeDq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=259847718&fsize=305374529&hid=11ebcd4213988e57481af625f75bf49e&media_type=compressed&tknv=v3&ts=64c3213a63780&s=a564b3ea58cc86d3c3a1d564fd088e8d45afde3b69e869346ce0d9312b4ef527&pb=U2FsdGVkX1-V5wpWXWFjf7GiYMFEpmiUlTjSKAcWjsAuUnFMIMleFGI67YVdXNrhR9Fi5BA7LU_CWlEjmwYg9EVoPecdEM0Rr9kvgIpm0KRr3GcfUTodQtnEXqUuLCI3 [following]
--2026-03-04 08:37:41--  https://s02klg.storage.yandex.net/rdisk/2cc0bb58fa52381e1088248dd2070aede68759a73fdeee494c05b7efd2022d65/69a8276e/fKqInKw3d7bLFOeFnMGnhOEt74e_AcHrfoeOiWQFqnxSx2KlJFe3moqi-rTFCO6djYu3q6EHAUP4X1BQu7yk7eyLDbl9lafVd4ruaDAPlxGr8npumZHI4midPdWhecNq?uid=0&filename=whos-talking-classify-the-app-by-its-packets.zip&disposition=attachment&hash=m8VLCd1u1YCGUik9dZVkJjbxXRNbrE0kS1p%2BEIBguw1klnm56L9GDaExZ6Yk0MeDq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=259847718&fsize=305374529&hid=11ebcd4213988e57481af625f75bf49e&media_type=compressed&tknv=v3&ts=64c3213a63780&s=a564b3ea58cc86d3c3a1d564fd088e8d45afde3b69e869346ce0d9312b4ef527&pb=U2FsdGVkX1-V5wpWXWFjf7GiYMFEpmiUlTjSKAcWjsAuUnFMIMleFGI67YVdXNrhR9Fi5BA7LU_CWlEjmwYg9EVoPecdEM0Rr9kvgIpm0KRr3GcfUTodQtnEXqUuLCI3
Resolving s02klg.storage.yandex.net (s02klg.storage.yandex.net)... 5.255.221.2, 2a02:6b8:c41:a4:0:41af:be4f:c060
Connecting to s02klg.storage.yandex.net (s02klg.storage.yandex.net)|5.255.221.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305374529 (291M) [application/zip]
Saving to: ‘archive.zip’

archive.zip         100%[===================>] 291.23M  22.1MB/s    in 15s

2026-03-04 08:37:58 (20.0 MB/s) - ‘archive.zip’ saved [305374529/305374529]

In [5]:
!unzip archive.zip -d data

Archive:  archive.zip
  inflating: data/sample_submission.csv
  inflating: data/test.csv
  inflating: data/train.csv

Установим необходимые библиотеки

In [6]:
!pip install catboost -q

import numpy as np
import pandas as pd
import gc

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from catboost import CatBoostClassifier, Pool

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.5 MB/s eta 0:00:00

Загрузим данные и посмотрим на них

In [7]:
df = pd.read_csv('/content/data/train.csv')

df.info()

/tmp/ipykernel_224/525312853.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/data/train.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8248546 entries, 0 to 8248545
Data columns (total 31 columns):
 #   Column       Dtype
---  ------       -----
 0   app_service  object
 1   tcp_len_1    int64
 2   tcp_len_2    float64
 3   tcp_len_3    float64
 4   tcp_len_4    float64
 5   tcp_len_5    float64
 6   tcp_len_6    float64
 7   tcp_len_7    float64
 8   tcp_len_8    float64
 9   tcp_len_9    float64
 10  tcp_len_10   float64
 11  tcp_len_11   float64
 12  tcp_len_12   float64
 13  tcp_len_13   float64
 14  tcp_len_14   float64
 15  tcp_len_15   float64
 16  tcp_len_16   float64
 17  tcp_len_17   float64
 18  tcp_len_18   float64
 19  tcp_len_19   float64
 20  tcp_len_20   float64
 21  tcp_len_21   float64
 22  tcp_len_22   float64
 23  tcp_len_23   float64
 24  tcp_len_24   float64
 25  tcp_len_25   float64
 26  tcp_len_26   float64
 27  tcp_len_27   float64
 28  tcp_len_28   float64
 29  tcp_len_29   float64
 30  tcp_len_30   float64
dtypes: float64(29), int64(1), object(1)
memory usage: 1.9+ GB

In [8]:
df.sample(5)

,app_service,tcp_len_1,tcp_len_2,tcp_len_3,tcp_len_4,tcp_len_5,tcp_len_6,tcp_len_7,tcp_len_8,tcp_len_9,...,tcp_len_21,tcp_len_22,tcp_len_23,tcp_len_24,tcp_len_25,tcp_len_26,tcp_len_27,tcp_len_28,tcp_len_29,tcp_len_30
5232697,kontur,1404,415.0,-1448.0,-1448.0,-1200.0,-333.0,80.0,92.0,398.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4424823,google,1412,880.0,-1412.0,-60.0,74.0,92.0,735.0,241.0,-976.0,...,-99.0,-31.0,-39.0,35.0,39.0,79.0,183.0,-70.0,-77.0,-31.0
7901659,yandex_mail,1410,1108.0,-1220.0,-1220.0,-1220.0,-436.0,-1118.0,80.0,-287.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5962866,mts,1460,326.0,-1460.0,-953.0,64.0,92.0,497.0,-271.0,-271.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2161936,Rutube,1410,676.0,-260.0,80.0,1410.0,1241.0,-287.0,-550.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df.memory_usage(deep=True).sum() / 1024**2

np.float64(2317.443407058716)

Казалось бы по определению длина - целая величина, а тут используеться float64, давайте экономить память. Проверим диапозон значений, найдем есть ли наны или инфы, проверим количество не целых чисел

In [10]:
target_col = "app_service"
feat_cols = [c for c in df.columns if c.startswith("tcp_len_")]
print(feat_cols)

['tcp_len_1', 'tcp_len_2', 'tcp_len_3', 'tcp_len_4', 'tcp_len_5', 'tcp_len_6', 'tcp_len_7', 'tcp_len_8', 'tcp_len_9', 'tcp_len_10', 'tcp_len_11', 'tcp_len_12', 'tcp_len_13', 'tcp_len_14', 'tcp_len_15', 'tcp_len_16', 'tcp_len_17', 'tcp_len_18', 'tcp_len_19', 'tcp_len_20', 'tcp_len_21', 'tcp_len_22', 'tcp_len_23', 'tcp_len_24', 'tcp_len_25', 'tcp_len_26', 'tcp_len_27', 'tcp_len_28', 'tcp_len_29', 'tcp_len_30']

In [11]:
stats = {
    "min_value": df[feat_cols].min().min(),
    "max_value": df[feat_cols].max().max(),
    "nan_count": np.isnan(df[feat_cols].values).sum(),
    "inf_count": np.isinf(df[feat_cols].values).sum(),
    "non_integer_count": np.sum((df[feat_cols].values % 1) != 0),
    "zero_value": np.sum((df[feat_cols].values == 0)),
}

stats

{'min_value': -1464.0,
 'max_value': 1460.0,
 'nan_count': np.int64(0),
 'inf_count': np.int64(0),
 'non_integer_count': np.int64(0),
 'zero_value': np.int64(75589496)}

Как видно значения по в диапозоне от -1464 до 1460 нет ни нанов ни инфов ни дробных чисел - изменим тип на int16

In [12]:
feat_cols = [c for c in df.columns if c.startswith("tcp_len_")]
df[feat_cols] = df[feat_cols].astype(np.int16)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8248546 entries, 0 to 8248545
Data columns (total 31 columns):
 #   Column       Dtype
---  ------       -----
 0   app_service  object
 1   tcp_len_1    int16
 2   tcp_len_2    int16
 3   tcp_len_3    int16
 4   tcp_len_4    int16
 5   tcp_len_5    int16
 6   tcp_len_6    int16
 7   tcp_len_7    int16
 8   tcp_len_8    int16
 9   tcp_len_9    int16
 10  tcp_len_10   int16
 11  tcp_len_11   int16
 12  tcp_len_12   int16
 13  tcp_len_13   int16
 14  tcp_len_14   int16
 15  tcp_len_15   int16
 16  tcp_len_16   int16
 17  tcp_len_17   int16
 18  tcp_len_18   int16
 19  tcp_len_19   int16
 20  tcp_len_20   int16
 21  tcp_len_21   int16
 22  tcp_len_22   int16
 23  tcp_len_23   int16
 24  tcp_len_24   int16
 25  tcp_len_25   int16
 26  tcp_len_26   int16
 27  tcp_len_27   int16
 28  tcp_len_28   int16
 29  tcp_len_29   int16
 30  tcp_len_30   int16
dtypes: int16(30), object(1)
memory usage: 534.9+ MB

In [13]:
df.memory_usage(deep=True).sum() / 1024**2

np.float64(901.4866428375244)

Почти в 4 раза экономнее, RAM в колабе скажет спасибо

In [14]:
N = len(df)
N

8248546

In [15]:
X0 = df[feat_cols]
y = df[target_col].astype(str)

sample_n = 1_000_000 # всё не влезет
idx = np.random.RandomState(42).choice(N, size=sample_n, replace=False)

X0 = X0.iloc[idx]
y  = y.iloc[idx]

Посмотрим на целевую переменную

In [16]:
y.value_counts()

app_service
Telegram        12315
287             12277
GMail           12277
Wildberries     12268
Teams           12266
                ...
apteka-ru         135
appdynamics       133
MEGA              131
razer-online      127
upto-like         124
Name: count, Length: 252, dtype: int64

In [17]:
set(y)

{'1',
 '1-password',
 '101-radio',
 '113',
 '120',
 '15',
 '218',
 '287',
 '299',
 '2gis',
 '343',
 '4',
 '93',
 'Amazon',
 'Anydesk',
 'Apple',
 'Baidu',
 'DataSaver',
 'DoH_DoT',
 'DropBox',
 'Facebook',
 'GMail',
 'Github',
 'Gitlab',
 'Instagram',
 'Ktalk',
 'LinkedIn',
 'Livejournal',
 'MEGA',
 'MSN',
 'Mattermost',
 'Odnoklassniki',
 'Ozon',
 'PlayStore',
 'Playstation',
 'QQ',
 'Quora',
 'Reddit',
 'Rutube',
 'Skype',
 'Snapchat',
 'SoundCloud',
 'Spotify',
 'Steam',
 'Teams',
 'Telegram',
 'TikTok',
 'Twitch',
 'Twitter',
 'WhatsApp',
 'Wikipedia',
 'Wildberries',
 'Yandex',
 'YouTube',
 'adblock-plus',
 'adobe',
 'aeroflot-online',
 'afisha-ru',
 'alfabank',
 'ali-wangwang-file-transfer',
 'alipay',
 'amd-online',
 'andata',
 'any-run',
 'anygo',
 'appdynamics',
 'apple-community',
 'apple-siri',
 'apple_icloud',
 'apple_push',
 'apteka-ru',
 'avito',
 'azure',
 'banki-ru',
 'beeline-online',
 'bing',
 'bitly',
 'blog-posting',
 'braintree',
 'bugsnag',
 'bybit',
 'ca-technologies',
 'cackle-widgets',
 'cardsmobile',
 'cdek',
 'chatra',
 'check-point-software-technologies',
 'cian',
 'citilink',
 'cloudflare.dns',
 'coub',
 'crazyegg',
 'createjs',
 'criteo-ads',
 'ctc-tv-online',
 'cursor',
 'dashlane',
 'datadog',
 'deepl',
 'demandbase',
 'directv',
 'disqus',
 'dns-shop',
 'docker',
 'domclick',
 'dotvpn',
 'drom-ru',
 'dzen',
 'eBay',
 'ea-fifa',
 'eapteka-online',
 'elastic',
 'emias',
 'epicgames',
 'evernote',
 'fastly',
 'felo-ai',
 'figma',
 'getcourse',
 'gigacode',
 'gismeteo',
 'gitbook',
 'google',
 'google_docs',
 'google_drive',
 'google_maps',
 'gosuslugi',
 'grammarly',
 'gravatar',
 'habr',
 'head-hunter',
 'holst',
 'hubspot',
 'huntflow',
 'ibm-kenexa-products',
 'imgur',
 'intercom',
 'jetbrains',
 'jsdelivr',
 'kaspersky',
 'kontur',
 'lamoda',
 'lastpass',
 'lenovo-online',
 'lens',
 'lichess',
 'litres',
 'mail_ru',
 'mailchimp',
 'mapbox',
 'matlab',
 'media-net',
 'mediatek-online',
 'metatrader',
 'microsoft',
 'mindbox',
 'miro',
 'miui-online',
 'moex-online',
 'mos-ru',
 'mozilla',
 'ms_onedrive',
 'mts',
 'multifactor',
 'nbc-video',
 'net-beans',
 'new-relic',
 'notion',
 'nuget',
 'nvidia',
 'office_365',
 'okko-tv',
 'opendrive',
 'otpbank-online',
 'password-box',
 'pikabu',
 'pinterest',
 'postman',
 'premier-tv',
 'profi-ru',
 'pushed',
 'pypi',
 'raiffeisen',
 'rambler',
 'razer-online',
 'realtimeboard',
 'reg-ru',
 'roblox',
 'ru-store',
 'samokat',
 'samsung-online',
 'samsung-updates',
 'sber_online',
 'segment',
 'sentry',
 'sharethrough',
 'shodan',
 'similarweb',
 'slack',
 'smotrim',
 'snapcraft',
 'split',
 'stackoverflow',
 'start',
 'stepik',
 'sway',
 't-bank',
 'taobao',
 'tech-target',
 'tembo-social',
 'teradata',
 'the-weather-channel',
 'tilda',
 'tinkoff',
 'tns-counter',
 'to-doist',
 'trading-view',
 'transneft-online',
 'trello',
 'tria',
 'tripster',
 'tv4play',
 'tweet-feed',
 'twinby',
 'ubuntu',
 'unity3d',
 'upbase',
 'upto-like',
 'vigo',
 'vimeo',
 'virustotal',
 'visual-studio',
 'vkontakte',
 'vtb',
 'wikiportal',
 'windows-defender-atp-endpoint',
 'windows-push-notifications',
 'windows_update',
 'wondershare',
 'workingvpn',
 'x5',
 'xbox-live',
 'xiaomi-online',
 'yahoo',
 'yandex_disk',
 'yandex_mail',
 'yandex_maps',
 'yandex_music',
 'yandex_video',
 'yonote',
 'zoom',
 'zvuk'}

### Feature engineering

In [18]:
X0.head()

,tcp_len_1,tcp_len_2,tcp_len_3,tcp_len_4,tcp_len_5,tcp_len_6,tcp_len_7,tcp_len_8,tcp_len_9,tcp_len_10,...,tcp_len_21,tcp_len_22,tcp_len_23,tcp_len_24,tcp_len_25,tcp_len_26,tcp_len_27,tcp_len_28,tcp_len_29,tcp_len_30
3899906,517,-1448,-1448,-1448,-23,64,992,-179,-62,-31,...,586,31,-251,1448,54,31,-305,-31,586,31
5090771,543,-399,51,234,-238,-1460,-1460,-1209,251,-1405,...,-1460,-633,245,-1405,-1460,-1460,-7,249,-1405,-1359
6160203,517,-203,314,-1460,-349,-1136,250,-1391,-1137,250,...,0,0,0,0,0,0,0,0,0,0
3764889,517,-1448,-1448,-579,64,1208,56,-1208,-1448,-946,...,0,0,0,0,0,0,0,0,0,0
7759903,1460,647,-1460,-1460,-1176,-1287,64,92,548,-287,...,0,0,0,0,0,0,0,0,0,0

In [19]:
X = X0.copy()

pos = (X0 > 0)
neg = (X0 < 0)
nonzero = (X0 != 0)
not_zeros = (X0.iloc[:, :-1].values != 0) & (X0.iloc[:, 1:].values != 0)
switches = (pos.iloc[:, :-1].values != pos.iloc[:, 1:].values)
switches_full = np.column_stack([np.zeros(switches.shape[0], dtype=bool), switches])

actual_switches = (switches_full & nonzero)
group_ids = np.cumsum(actual_switches, axis=1)
first_request = np.where(group_ids == 0, X0.values, 0)
first_response = np.where(group_ids == 1, X0.values, 0)
second_request = np.where(group_ids == 2, X0.values, 0)
second_response = np.where(group_ids == 3, X0.values, 0)
third_request = np.where(group_ids == 4, X0.values, 0)
third_response = np.where(group_ids == 5, X0.values, 0)
fourth_request = np.where(group_ids == 6, X0.values, 0)
fourth_response = np.where(group_ids == 7, X0.values, 0)
fifth_request = np.where(group_ids == 8, X0.values, 0)
fifth_response = np.where(group_ids == 9, X0.values, 0)

X["pkt_cnt"] = nonzero.sum(axis=1).astype(np.int16) # общее количество пакетов в потоке
X["n_up"]    = pos.sum(axis=1).astype(np.int16) # количество пакетов от клиента
X["n_down"]  = neg.sum(axis=1).astype(np.int16) # количество пакетов от сервера

X["bytes_up"]   = X0.where(pos, 0).sum(axis=1).astype(np.int32) # суммарное количество байт, отправленных клиентом
X["bytes_down"] = (-X0.where(neg, 0)).sum(axis=1).astype(np.int32) # суммарное количество байт, полученных от сервера
X["total_switches"] = (actual_switches.sum(axis=1)).astype(np.int16) # количество смен направлений
X["first_request"] = np.sum(first_request, axis=1)
X["first_response"] = np.sum(first_response, axis=1)
X["second_request"] = np.sum(second_request, axis=1)
X["second_response"] = np.sum(second_response, axis=1)
X["third_request"] = np.sum(third_request, axis=1)
X["third_response"] = np.sum(third_response, axis=1)
X["fourth_request"] = np.sum(fourth_request, axis=1)
X["fourth_response"] = np.sum(fourth_response, axis=1)
X["fifth_request"] = np.sum(fifth_request, axis=1)
X["fifth_response"] = np.sum(fifth_response, axis=1)


print(X["total_switches"].min().min())
print(X["total_switches"].max().max())
print(X["total_switches"].mode()[0])


print(X.iloc[0])
print(switches_full[0])

0
29
5
tcp_len_1           517
tcp_len_2         -1448
tcp_len_3         -1448
tcp_len_4         -1448
tcp_len_5           -23
tcp_len_6            64
tcp_len_7           992
tcp_len_8          -179
tcp_len_9           -62
tcp_len_10          -31
tcp_len_11          -35
tcp_len_12           31
tcp_len_13         -251
tcp_len_14           31
tcp_len_15         1448
tcp_len_16          162
tcp_len_17          -35
tcp_len_18           31
tcp_len_19         -305
tcp_len_20          -31
tcp_len_21          586
tcp_len_22           31
tcp_len_23         -251
tcp_len_24         1448
tcp_len_25           54
tcp_len_26           31
tcp_len_27         -305
tcp_len_28          -31
tcp_len_29          586
tcp_len_30           31
pkt_cnt              30
n_up                 15
n_down               15
bytes_up           6043
bytes_down         5883
total_switches       14
first_request       517
first_response    -4367
second_request     1056
second_response    -307
third_request        31
third_response     -251
fourth_request     1641
fourth_response     -35
fifth_request        31
fifth_response     -336
Name: 3899906, dtype: int64
[False  True False False False  True False  True False False False  True
  True  True False False  True  True  True False  True False  True  True
 False False  True False  True False]

### Обучение модели и валидация

In [20]:
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [21]:
model = CatBoostClassifier(
    loss_function="MultiClass",
    eval_metric="TotalF1",
    auto_class_weights='Balanced',
    # custom_metric=["Precision", "Recall", "Accuracy"],
    iterations=250,
    depth=10,
    learning_rate=0.15,
    random_seed=42,
    verbose=True,
    task_type="GPU",
    devices="0"
)

model.fit(
    X_train, y_train,
    eval_set=(X_val, y_val),
    use_best_model=True
)

pred = model.predict(X_val).reshape(-1)
print("val accuracy:", accuracy_score(y_val, pred))

0:	learn: 0.2249258	test: 0.2169201	best: 0.2169201 (0)	total: 10.3s	remaining: 42m 42s
1:	learn: 0.2480010	test: 0.2431540	best: 0.2431540 (1)	total: 18.7s	remaining: 38m 41s
2:	learn: 0.2714840	test: 0.2651989	best: 0.2651989 (2)	total: 27.5s	remaining: 37m 42s
3:	learn: 0.3422502	test: 0.3357996	best: 0.3357996 (3)	total: 37.9s	remaining: 38m 53s
4:	learn: 0.3624045	test: 0.3589908	best: 0.3589908 (4)	total: 46.2s	remaining: 37m 41s
5:	learn: 0.3813159	test: 0.3766863	best: 0.3766863 (5)	total: 55.2s	remaining: 37m 24s
6:	learn: 0.4117643	test: 0.4043336	best: 0.4043336 (6)	total: 1m 5s	remaining: 37m 56s
7:	learn: 0.4441605	test: 0.4333640	best: 0.4333640 (7)	total: 1m 13s	remaining: 37m 4s
8:	learn: 0.4721334	test: 0.4609169	best: 0.4609169 (8)	total: 1m 22s	remaining: 36m 47s
9:	learn: 0.4967259	test: 0.4846353	best: 0.4846353 (9)	total: 1m 32s	remaining: 36m 51s
10:	learn: 0.5268994	test: 0.5093865	best: 0.5093865 (10)	total: 1m 41s	remaining: 36m 51s
11:	learn: 0.5423320	test: 0.5229253	best: 0.5229253 (11)	total: 1m 50s	remaining: 36m 32s
12:	learn: 0.5649011	test: 0.5430781	best: 0.5430781 (12)	total: 2m 2s	remaining: 37m 7s
13:	learn: 0.5947197	test: 0.5684912	best: 0.5684912 (13)	total: 2m 11s	remaining: 36m 52s
14:	learn: 0.6139400	test: 0.5865506	best: 0.5865506 (14)	total: 2m 20s	remaining: 36m 40s
15:	learn: 0.6375460	test: 0.6048127	best: 0.6048127 (15)	total: 2m 31s	remaining: 36m 48s
16:	learn: 0.6515273	test: 0.6174833	best: 0.6174833 (16)	total: 2m 39s	remaining: 36m 29s
17:	learn: 0.6625219	test: 0.6271552	best: 0.6271552 (17)	total: 2m 48s	remaining: 36m 8s
18:	learn: 0.6714523	test: 0.6356514	best: 0.6356514 (18)	total: 2m 58s	remaining: 36m 9s
19:	learn: 0.6846128	test: 0.6460509	best: 0.6460509 (19)	total: 3m 7s	remaining: 35m 54s
20:	learn: 0.6954210	test: 0.6557272	best: 0.6557272 (20)	total: 3m 16s	remaining: 35m 45s
21:	learn: 0.7049879	test: 0.6635516	best: 0.6635516 (21)	total: 3m 27s	remaining: 35m 48s
22:	learn: 0.7119976	test: 0.6689045	best: 0.6689045 (22)	total: 3m 36s	remaining: 35m 37s
23:	learn: 0.7170824	test: 0.6739081	best: 0.6739081 (23)	total: 3m 44s	remaining: 35m 18s
24:	learn: 0.7234266	test: 0.6777735	best: 0.6777735 (24)	total: 3m 55s	remaining: 35m 17s
25:	learn: 0.7339074	test: 0.6864445	best: 0.6864445 (25)	total: 4m 3s	remaining: 35m
26:	learn: 0.7394734	test: 0.6909815	best: 0.6909815 (26)	total: 4m 12s	remaining: 34m 43s
27:	learn: 0.7453232	test: 0.6957652	best: 0.6957652 (27)	total: 4m 22s	remaining: 34m 42s
28:	learn: 0.7523639	test: 0.7034315	best: 0.7034315 (28)	total: 4m 31s	remaining: 34m 25s
29:	learn: 0.7592289	test: 0.7088767	best: 0.7088767 (29)	total: 4m 40s	remaining: 34m 14s
30:	learn: 0.7665705	test: 0.7145940	best: 0.7145940 (30)	total: 4m 51s	remaining: 34m 21s
31:	learn: 0.7720433	test: 0.7178687	best: 0.7178687 (31)	total: 5m 1s	remaining: 34m 12s
32:	learn: 0.7766223	test: 0.7213290	best: 0.7213290 (32)	total: 5m 10s	remaining: 34m 4s
33:	learn: 0.7810941	test: 0.7249966	best: 0.7249966 (33)	total: 5m 21s	remaining: 34m
34:	learn: 0.7838679	test: 0.7275973	best: 0.7275973 (34)	total: 5m 29s	remaining: 33m 43s
35:	learn: 0.7869250	test: 0.7297767	best: 0.7297767 (35)	total: 5m 38s	remaining: 33m 30s
36:	learn: 0.7864798	test: 0.7285066	best: 0.7297767 (35)	total: 5m 48s	remaining: 33m 24s
37:	learn: 0.7925449	test: 0.7351192	best: 0.7351192 (37)	total: 5m 57s	remaining: 33m 15s
38:	learn: 0.7970668	test: 0.7383603	best: 0.7383603 (38)	total: 6m 7s	remaining: 33m 9s
39:	learn: 0.8027737	test: 0.7423409	best: 0.7423409 (39)	total: 6m 18s	remaining: 33m 5s
40:	learn: 0.8068469	test: 0.7467008	best: 0.7467008 (40)	total: 6m 27s	remaining: 32m 55s
41:	learn: 0.8098799	test: 0.7485155	best: 0.7485155 (41)	total: 6m 36s	remaining: 32m 41s
42:	learn: 0.8138579	test: 0.7516401	best: 0.7516401 (42)	total: 6m 46s	remaining: 32m 35s
43:	learn: 0.8171064	test: 0.7551482	best: 0.7551482 (43)	total: 6m 54s	remaining: 32m 22s
44:	learn: 0.8203210	test: 0.7580135	best: 0.7580135 (44)	total: 7m 4s	remaining: 32m 13s
45:	learn: 0.8229909	test: 0.7603529	best: 0.7603529 (45)	total: 7m 14s	remaining: 32m 8s
46:	learn: 0.8254097	test: 0.7615946	best: 0.7615946 (46)	total: 7m 22s	remaining: 31m 52s
47:	learn: 0.8277211	test: 0.7636507	best: 0.7636507 (47)	total: 7m 32s	remaining: 31m 43s
48:	learn: 0.8301305	test: 0.7650839	best: 0.7650839 (48)	total: 7m 42s	remaining: 31m 38s
49:	learn: 0.8334091	test: 0.7676922	best: 0.7676922 (49)	total: 7m 52s	remaining: 31m 28s
50:	learn: 0.8347490	test: 0.7691673	best: 0.7691673 (50)	total: 8m 1s	remaining: 31m 20s
51:	learn: 0.8370696	test: 0.7715827	best: 0.7715827 (51)	total: 8m 11s	remaining: 31m 11s
52:	learn: 0.8388811	test: 0.7726802	best: 0.7726802 (52)	total: 8m 20s	remaining: 30m 59s
53:	learn: 0.8399109	test: 0.7735401	best: 0.7735401 (53)	total: 8m 28s	remaining: 30m 47s
54:	learn: 0.8416795	test: 0.7741958	best: 0.7741958 (54)	total: 8m 39s	remaining: 30m 42s
55:	learn: 0.8423996	test: 0.7750446	best: 0.7750446 (55)	total: 8m 48s	remaining: 30m 30s
56:	learn: 0.8441216	test: 0.7763310	best: 0.7763310 (56)	total: 8m 57s	remaining: 30m 20s
57:	learn: 0.8459006	test: 0.7778604	best: 0.7778604 (57)	total: 9m 7s	remaining: 30m 13s
58:	learn: 0.8476280	test: 0.7788458	best: 0.7788458 (58)	total: 9m 16s	remaining: 30m 1s
59:	learn: 0.8495642	test: 0.7802775	best: 0.7802775 (59)	total: 9m 25s	remaining: 29m 50s
60:	learn: 0.8513712	test: 0.7814609	best: 0.7814609 (60)	total: 9m 35s	remaining: 29m 43s
61:	learn: 0.8533196	test: 0.7828261	best: 0.7828261 (61)	total: 9m 44s	remaining: 29m 31s
62:	learn: 0.8554115	test: 0.7843350	best: 0.7843350 (62)	total: 9m 53s	remaining: 29m 21s
63:	learn: 0.8581487	test: 0.7865732	best: 0.7865732 (63)	total: 10m 3s	remaining: 29m 15s
64:	learn: 0.8595674	test: 0.7878287	best: 0.7878287 (64)	total: 10m 12s	remaining: 29m 4s
65:	learn: 0.8607787	test: 0.7889881	best: 0.7889881 (65)	total: 10m 21s	remaining: 28m 52s
66:	learn: 0.8621152	test: 0.7898349	best: 0.7898349 (66)	total: 10m 31s	remaining: 28m 46s
67:	learn: 0.8638617	test: 0.7908783	best: 0.7908783 (67)	total: 10m 40s	remaining: 28m 34s
68:	learn: 0.8652502	test: 0.7920415	best: 0.7920415 (68)	total: 10m 49s	remaining: 28m 23s
69:	learn: 0.8665897	test: 0.7934916	best: 0.7934916 (69)	total: 10m 58s	remaining: 28m 14s
70:	learn: 0.8690895	test: 0.7952885	best: 0.7952885 (70)	total: 11m 8s	remaining: 28m 4s
71:	learn: 0.8700200	test: 0.7955793	best: 0.7955793 (71)	total: 11m 17s	remaining: 27m 54s
72:	learn: 0.8717634	test: 0.7967622	best: 0.7967622 (72)	total: 11m 28s	remaining: 27m 49s
73:	learn: 0.8732549	test: 0.7978757	best: 0.7978757 (73)	total: 11m 37s	remaining: 27m 39s
74:	learn: 0.8745226	test: 0.7985890	best: 0.7985890 (74)	total: 11m 47s	remaining: 27m 30s
75:	learn: 0.8750322	test: 0.7990241	best: 0.7990241 (75)	total: 11m 57s	remaining: 27m 22s
76:	learn: 0.8759628	test: 0.7992699	best: 0.7992699 (76)	total: 12m 6s	remaining: 27m 11s
77:	learn: 0.8767587	test: 0.7997447	best: 0.7997447 (77)	total: 12m 15s	remaining: 27m 1s
78:	learn: 0.8780656	test: 0.8008755	best: 0.8008755 (78)	total: 12m 25s	remaining: 26m 52s
79:	learn: 0.8792176	test: 0.8019163	best: 0.8019163 (79)	total: 12m 33s	remaining: 26m 41s
80:	learn: 0.8796204	test: 0.8022524	best: 0.8022524 (80)	total: 12m 42s	remaining: 26m 31s
81:	learn: 0.8799782	test: 0.8031046	best: 0.8031046 (81)	total: 12m 52s	remaining: 26m 22s
82:	learn: 0.8819567	test: 0.8039815	best: 0.8039815 (82)	total: 13m 1s	remaining: 26m 12s
83:	learn: 0.8824520	test: 0.8042331	best: 0.8042331 (83)	total: 13m 10s	remaining: 26m 2s
84:	learn: 0.8836631	test: 0.8049736	best: 0.8049736 (84)	total: 13m 20s	remaining: 25m 53s
85:	learn: 0.8846691	test: 0.8057423	best: 0.8057423 (85)	total: 13m 28s	remaining: 25m 42s
86:	learn: 0.8857763	test: 0.8071854	best: 0.8071854 (86)	total: 13m 37s	remaining: 25m 31s
87:	learn: 0.8865006	test: 0.8081486	best: 0.8081486 (87)	total: 13m 46s	remaining: 25m 22s
88:	learn: 0.8873680	test: 0.8096700	best: 0.8096700 (88)	total: 13m 55s	remaining: 25m 12s
89:	learn: 0.8887836	test: 0.8103594	best: 0.8103594 (89)	total: 14m 5s	remaining: 25m 2s
90:	learn: 0.8901535	test: 0.8109961	best: 0.8109961 (90)	total: 14m 14s	remaining: 24m 53s
91:	learn: 0.8909226	test: 0.8119869	best: 0.8119869 (91)	total: 14m 23s	remaining: 24m 43s
92:	learn: 0.8920142	test: 0.8132554	best: 0.8132554 (92)	total: 14m 33s	remaining: 24m 34s
93:	learn: 0.8928152	test: 0.8140686	best: 0.8140686 (93)	total: 14m 42s	remaining: 24m 24s
94:	learn: 0.8938115	test: 0.8144900	best: 0.8144900 (94)	total: 14m 51s	remaining: 24m 14s
95:	learn: 0.8944737	test: 0.8149895	best: 0.8149895 (95)	total: 15m	remaining: 24m 4s
96:	learn: 0.8948359	test: 0.8151438	best: 0.8151438 (96)	total: 15m 8s	remaining: 23m 53s
97:	learn: 0.8959258	test: 0.8161173	best: 0.8161173 (97)	total: 15m 18s	remaining: 23m 44s
98:	learn: 0.8965857	test: 0.8169388	best: 0.8169388 (98)	total: 15m 27s	remaining: 23m 35s
99:	learn: 0.8978676	test: 0.8173735	best: 0.8173735 (99)	total: 15m 36s	remaining: 23m 24s
100:	learn: 0.8988073	test: 0.8184147	best: 0.8184147 (100)	total: 15m 45s	remaining: 23m 15s
101:	learn: 0.8996333	test: 0.8189510	best: 0.8189510 (101)	total: 15m 56s	remaining: 23m 7s
102:	learn: 0.9007055	test: 0.8191817	best: 0.8191817 (102)	total: 16m 5s	remaining: 22m 57s
103:	learn: 0.9010984	test: 0.8195429	best: 0.8195429 (103)	total: 16m 13s	remaining: 22m 46s
104:	learn: 0.9014314	test: 0.8202915	best: 0.8202915 (104)	total: 16m 23s	remaining: 22m 38s
105:	learn: 0.9013862	test: 0.8197388	best: 0.8202915 (104)	total: 16m 31s	remaining: 22m 27s
106:	learn: 0.9023299	test: 0.8207707	best: 0.8207707 (106)	total: 16m 40s	remaining: 22m 16s
107:	learn: 0.9030338	test: 0.8216177	best: 0.8216177 (107)	total: 16m 50s	remaining: 22m 8s
108:	learn: 0.9033357	test: 0.8221052	best: 0.8221052 (108)	total: 16m 59s	remaining: 21m 58s
109:	learn: 0.9042848	test: 0.8226413	best: 0.8226413 (109)	total: 17m 8s	remaining: 21m 49s
110:	learn: 0.9050079	test: 0.8236235	best: 0.8236235 (110)	total: 17m 18s	remaining: 21m 40s
111:	learn: 0.9059451	test: 0.8236679	best: 0.8236679 (111)	total: 17m 27s	remaining: 21m 30s
112:	learn: 0.9067362	test: 0.8246040	best: 0.8246040 (112)	total: 17m 35s	remaining: 21m 20s
113:	learn: 0.9073597	test: 0.8251904	best: 0.8251904 (113)	total: 17m 46s	remaining: 21m 11s
114:	learn: 0.9080351	test: 0.8256551	best: 0.8256551 (114)	total: 17m 56s	remaining: 21m 3s
115:	learn: 0.9095686	test: 0.8265366	best: 0.8265366 (115)	total: 18m 6s	remaining: 20m 55s
116:	learn: 0.9100139	test: 0.8272394	best: 0.8272394 (116)	total: 18m 16s	remaining: 20m 46s
117:	learn: 0.9104049	test: 0.8274415	best: 0.8274415 (117)	total: 18m 24s	remaining: 20m 35s
118:	learn: 0.9113672	test: 0.8280859	best: 0.8280859 (118)	total: 18m 34s	remaining: 20m 26s
119:	learn: 0.9119021	test: 0.8283427	best: 0.8283427 (119)	total: 18m 44s	remaining: 20m 18s
120:	learn: 0.9127009	test: 0.8291853	best: 0.8291853 (120)	total: 18m 53s	remaining: 20m 8s
121:	learn: 0.9139106	test: 0.8298953	best: 0.8298953 (121)	total: 19m 3s	remaining: 19m 59s
122:	learn: 0.9144678	test: 0.8301064	best: 0.8301064 (122)	total: 19m 13s	remaining: 19m 50s
123:	learn: 0.9147660	test: 0.8304195	best: 0.8304195 (123)	total: 19m 21s	remaining: 19m 40s
124:	learn: 0.9152491	test: 0.8301587	best: 0.8304195 (123)	total: 19m 30s	remaining: 19m 30s
125:	learn: 0.9158644	test: 0.8305815	best: 0.8305815 (125)	total: 19m 39s	remaining: 19m 20s
126:	learn: 0.9163850	test: 0.8314505	best: 0.8314505 (126)	total: 19m 48s	remaining: 19m 10s
127:	learn: 0.9171240	test: 0.8318199	best: 0.8318199 (127)	total: 19m 57s	remaining: 19m 1s
128:	learn: 0.9175533	test: 0.8323320	best: 0.8323320 (128)	total: 20m 6s	remaining: 18m 51s
129:	learn: 0.9180735	test: 0.8328827	best: 0.8328827 (129)	total: 20m 15s	remaining: 18m 41s
130:	learn: 0.9184772	test: 0.8329365	best: 0.8329365 (130)	total: 20m 24s	remaining: 18m 32s
131:	learn: 0.9190589	test: 0.8336282	best: 0.8336282 (131)	total: 20m 32s	remaining: 18m 22s
132:	learn: 0.9196396	test: 0.8338997	best: 0.8338997 (132)	total: 20m 43s	remaining: 18m 13s
133:	learn: 0.9200039	test: 0.8341743	best: 0.8341743 (133)	total: 20m 52s	remaining: 18m 4s
134:	learn: 0.9202366	test: 0.8345232	best: 0.8345232 (134)	total: 21m 1s	remaining: 17m 54s
135:	learn: 0.9206783	test: 0.8343515	best: 0.8345232 (134)	total: 21m 10s	remaining: 17m 44s
136:	learn: 0.9212758	test: 0.8352453	best: 0.8352453 (136)	total: 21m 20s	remaining: 17m 36s
137:	learn: 0.9218035	test: 0.8356624	best: 0.8356624 (137)	total: 21m 28s	remaining: 17m 25s
138:	learn: 0.9222823	test: 0.8361614	best: 0.8361614 (138)	total: 21m 37s	remaining: 17m 15s
139:	learn: 0.9227687	test: 0.8367301	best: 0.8367301 (139)	total: 21m 47s	remaining: 17m 7s
140:	learn: 0.9231408	test: 0.8363894	best: 0.8367301 (139)	total: 21m 56s	remaining: 16m 58s
141:	learn: 0.9238467	test: 0.8366622	best: 0.8367301 (139)	total: 22m 5s	remaining: 16m 48s
142:	learn: 0.9242539	test: 0.8364014	best: 0.8367301 (139)	total: 22m 15s	remaining: 16m 39s
143:	learn: 0.9244678	test: 0.8369672	best: 0.8369672 (143)	total: 22m 23s	remaining: 16m 28s
144:	learn: 0.9249098	test: 0.8372721	best: 0.8372721 (144)	total: 22m 32s	remaining: 16m 19s
145:	learn: 0.9259127	test: 0.8378000	best: 0.8378000 (145)	total: 22m 43s	remaining: 16m 11s
146:	learn: 0.9266522	test: 0.8384519	best: 0.8384519 (146)	total: 22m 52s	remaining: 16m 1s
147:	learn: 0.9271681	test: 0.8386891	best: 0.8386891 (147)	total: 23m 1s	remaining: 15m 51s
148:	learn: 0.9275886	test: 0.8389785	best: 0.8389785 (148)	total: 23m 10s	remaining: 15m 42s
149:	learn: 0.9280037	test: 0.8394011	best: 0.8394011 (149)	total: 23m 19s	remaining: 15m 32s
150:	learn: 0.9283423	test: 0.8398102	best: 0.8398102 (150)	total: 23m 28s	remaining: 15m 23s
151:	learn: 0.9287290	test: 0.8398482	best: 0.8398482 (151)	total: 23m 36s	remaining: 15m 13s
152:	learn: 0.9291508	test: 0.8402558	best: 0.8402558 (152)	total: 23m 46s	remaining: 15m 4s
153:	learn: 0.9295334	test: 0.8398097	best: 0.8402558 (152)	total: 23m 55s	remaining: 14m 55s
154:	learn: 0.9299055	test: 0.8401745	best: 0.8402558 (152)	total: 24m 4s	remaining: 14m 45s
155:	learn: 0.9301266	test: 0.8407402	best: 0.8407402 (155)	total: 24m 11s	remaining: 14m 34s
156:	learn: 0.9304115	test: 0.8411274	best: 0.8411274 (156)	total: 24m 22s	remaining: 14m 26s
157:	learn: 0.9306556	test: 0.8408168	best: 0.8411274 (156)	total: 24m 30s	remaining: 14m 16s
158:	learn: 0.9308966	test: 0.8407687	best: 0.8411274 (156)	total: 24m 39s	remaining: 14m 6s
159:	learn: 0.9311620	test: 0.8408048	best: 0.8411274 (156)	total: 24m 50s	remaining: 13m 58s
160:	learn: 0.9313552	test: 0.8411482	best: 0.8411482 (160)	total: 24m 58s	remaining: 13m 48s
161:	learn: 0.9316478	test: 0.8414615	best: 0.8414615 (161)	total: 25m 7s	remaining: 13m 38s
162:	learn: 0.9320254	test: 0.8414931	best: 0.8414931 (162)	total: 25m 16s	remaining: 13m 29s
163:	learn: 0.9322673	test: 0.8419945	best: 0.8419945 (163)	total: 25m 25s	remaining: 13m 19s
164:	learn: 0.9329525	test: 0.8421148	best: 0.8421148 (164)	total: 25m 35s	remaining: 13m 10s
165:	learn: 0.9331824	test: 0.8421445	best: 0.8421445 (165)	total: 25m 43s	remaining: 13m
166:	learn: 0.9334730	test: 0.8427745	best: 0.8427745 (166)	total: 25m 52s	remaining: 12m 51s
167:	learn: 0.9337771	test: 0.8430040	best: 0.8430040 (167)	total: 26m 2s	remaining: 12m 42s
168:	learn: 0.9340455	test: 0.8429825	best: 0.8430040 (167)	total: 26m 10s	remaining: 12m 32s
169:	learn: 0.9343080	test: 0.8429660	best: 0.8430040 (167)	total: 26m 19s	remaining: 12m 23s
170:	learn: 0.9346735	test: 0.8429717	best: 0.8430040 (167)	total: 26m 29s	remaining: 12m 14s
171:	learn: 0.9349295	test: 0.8430672	best: 0.8430672 (171)	total: 26m 38s	remaining: 12m 4s
172:	learn: 0.9352143	test: 0.8432344	best: 0.8432344 (172)	total: 26m 47s	remaining: 11m 55s
173:	learn: 0.9355689	test: 0.8434278	best: 0.8434278 (173)	total: 26m 56s	remaining: 11m 46s
174:	learn: 0.9357849	test: 0.8429695	best: 0.8434278 (173)	total: 27m 5s	remaining: 11m 36s
175:	learn: 0.9361402	test: 0.8432475	best: 0.8434278 (173)	total: 27m 15s	remaining: 11m 27s
176:	learn: 0.9361269	test: 0.8430769	best: 0.8434278 (173)	total: 27m 24s	remaining: 11m 18s
177:	learn: 0.9363905	test: 0.8433071	best: 0.8434278 (173)	total: 27m 33s	remaining: 11m 8s
178:	learn: 0.9368560	test: 0.8435100	best: 0.8435100 (178)	total: 27m 42s	remaining: 10m 59s
179:	learn: 0.9370950	test: 0.8439930	best: 0.8439930 (179)	total: 27m 50s	remaining: 10m 49s
180:	learn: 0.9372542	test: 0.8436743	best: 0.8439930 (179)	total: 27m 59s	remaining: 10m 40s
181:	learn: 0.9375812	test: 0.8434807	best: 0.8439930 (179)	total: 28m 9s	remaining: 10m 31s
182:	learn: 0.9377545	test: 0.8436700	best: 0.8439930 (179)	total: 28m 18s	remaining: 10m 21s
183:	learn: 0.9379072	test: 0.8437440	best: 0.8439930 (179)	total: 28m 27s	remaining: 10m 12s
184:	learn: 0.9383619	test: 0.8441635	best: 0.8441635 (184)	total: 28m 36s	remaining: 10m 3s
185:	learn: 0.9384554	test: 0.8443664	best: 0.8443664 (185)	total: 28m 45s	remaining: 9m 53s
186:	learn: 0.9387202	test: 0.8444158	best: 0.8444158 (186)	total: 28m 54s	remaining: 9m 44s
187:	learn: 0.9389935	test: 0.8445470	best: 0.8445470 (187)	total: 29m 3s	remaining: 9m 34s
188:	learn: 0.9391021	test: 0.8447402	best: 0.8447402 (188)	total: 29m 12s	remaining: 9m 25s
189:	learn: 0.9393382	test: 0.8449045	best: 0.8449045 (189)	total: 29m 21s	remaining: 9m 16s
190:	learn: 0.9395016	test: 0.8449229	best: 0.8449229 (190)	total: 29m 30s	remaining: 9m 6s
191:	learn: 0.9397490	test: 0.8452248	best: 0.8452248 (191)	total: 29m 39s	remaining: 8m 57s
192:	learn: 0.9399612	test: 0.8454454	best: 0.8454454 (192)	total: 29m 49s	remaining: 8m 48s
193:	learn: 0.9403642	test: 0.8457721	best: 0.8457721 (193)	total: 29m 57s	remaining: 8m 39s
194:	learn: 0.9407871	test: 0.8461424	best: 0.8461424 (194)	total: 30m 6s	remaining: 8m 29s
195:	learn: 0.9409011	test: 0.8460885	best: 0.8461424 (194)	total: 30m 16s	remaining: 8m 20s
196:	learn: 0.9411976	test: 0.8462313	best: 0.8462313 (196)	total: 30m 25s	remaining: 8m 11s
197:	learn: 0.9414384	test: 0.8460731	best: 0.8462313 (196)	total: 30m 33s	remaining: 8m 1s
198:	learn: 0.9415172	test: 0.8463260	best: 0.8463260 (198)	total: 30m 42s	remaining: 7m 52s
199:	learn: 0.9416376	test: 0.8466869	best: 0.8466869 (199)	total: 30m 52s	remaining: 7m 43s
200:	learn: 0.9417954	test: 0.8465317	best: 0.8466869 (199)	total: 31m 1s	remaining: 7m 33s
201:	learn: 0.9420234	test: 0.8462111	best: 0.8466869 (199)	total: 31m 9s	remaining: 7m 24s
202:	learn: 0.9423570	test: 0.8465459	best: 0.8466869 (199)	total: 31m 19s	remaining: 7m 15s
203:	learn: 0.9425201	test: 0.8465321	best: 0.8466869 (199)	total: 31m 29s	remaining: 7m 6s
204:	learn: 0.9427744	test: 0.8466434	best: 0.8466869 (199)	total: 31m 37s	remaining: 6m 56s
205:	learn: 0.9429656	test: 0.8467856	best: 0.8467856 (205)	total: 31m 46s	remaining: 6m 47s
206:	learn: 0.9433066	test: 0.8463919	best: 0.8467856 (205)	total: 31m 57s	remaining: 6m 38s
207:	learn: 0.9434045	test: 0.8468794	best: 0.8468794 (207)	total: 32m 5s	remaining: 6m 28s
208:	learn: 0.9435976	test: 0.8471415	best: 0.8471415 (208)	total: 32m 14s	remaining: 6m 19s
209:	learn: 0.9438700	test: 0.8471289	best: 0.8471415 (208)	total: 32m 24s	remaining: 6m 10s
210:	learn: 0.9441036	test: 0.8475767	best: 0.8475767 (210)	total: 32m 33s	remaining: 6m 1s
211:	learn: 0.9443855	test: 0.8479726	best: 0.8479726 (211)	total: 32m 43s	remaining: 5m 51s
212:	learn: 0.9445800	test: 0.8478527	best: 0.8479726 (211)	total: 32m 53s	remaining: 5m 42s
213:	learn: 0.9448028	test: 0.8479957	best: 0.8479957 (213)	total: 33m 1s	remaining: 5m 33s
214:	learn: 0.9449730	test: 0.8479751	best: 0.8479957 (213)	total: 33m 9s	remaining: 5m 23s
215:	learn: 0.9452038	test: 0.8484681	best: 0.8484681 (215)	total: 33m 18s	remaining: 5m 14s
216:	learn: 0.9453449	test: 0.8486620	best: 0.8486620 (216)	total: 33m 26s	remaining: 5m 5s

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_val, pred))

                                   precision    recall  f1-score   support

                                1       0.88      0.80      0.84      2414
                       1-password       0.47      0.76      0.58        62
                        101-radio       0.69      0.74      0.71        27
                              113       0.97      0.93      0.95      2416
                              120       0.88      0.87      0.88      2417
                               15       0.76      0.97      0.85       538
                              218       0.91      0.95      0.93        82
                              287       0.93      0.97      0.95      2455
                              299       0.92      0.92      0.92      2453
                             2gis       0.96      0.92      0.94      1821
                              343       0.51      0.57      0.54      2437
                                4       0.88      0.89      0.89      2426
                               93       0.51      0.42      0.46      2410
                           Amazon       0.91      0.77      0.84      1994
                          Anydesk       0.94      1.00      0.97        31
                            Apple       0.80      0.54      0.65      2420
                            Baidu       0.76      0.90      0.82       158
                        DataSaver       1.00      1.00      1.00      2426
                          DoH_DoT       0.98      0.94      0.96      2399
                          DropBox       0.98      0.97      0.97      2298
                         Facebook       0.73      0.86      0.79       259
                            GMail       1.00      1.00      1.00      2455
                           Github       0.94      0.87      0.91      2412
                           Gitlab       0.87      0.88      0.87       523
                        Instagram       0.79      0.81      0.80        27
                            Ktalk       0.72      0.82      0.77      2445
                         LinkedIn       0.57      0.81      0.67       185
                      Livejournal       0.29      0.44      0.35        48
                             MEGA       0.26      0.54      0.35        26
                              MSN       0.94      0.94      0.94      2402
                       Mattermost       0.64      0.98      0.78        50
                    Odnoklassniki       0.95      0.95      0.95       997
                             Ozon       0.95      0.88      0.91      2428
                        PlayStore       0.95      0.95      0.95      1790
                      Playstation       0.88      0.89      0.89       274
                               QQ       0.67      0.88      0.76       155
                            Quora       0.78      0.88      0.83        59
                           Reddit       0.85      0.88      0.86      1534
                           Rutube       0.91      0.80      0.85      2412
                            Skype       0.92      0.91      0.92      2250
                         Snapchat       0.74      0.84      0.79       200
                       SoundCloud       0.42      0.77      0.54        56
                          Spotify       0.89      0.93      0.91       443
                            Steam       0.55      0.69      0.61       205
                            Teams       0.95      0.92      0.94      2453
                         Telegram       0.98      0.97      0.98      2463
                           TikTok       0.95      0.93      0.94      2426
                           Twitch       0.47      0.67      0.55       147
                          Twitter       0.50      0.63      0.56        57
                         WhatsApp       0.97      0.95      0.96      2437
                        Wikipedia       0.88      0.90      0.89       516
                      Wildberries       0.95      0.89      0.92      2454
                           Yandex       0.92      0.85      0.89      2430
                          YouTube       0.83      0.90      0.86      1187
                     adblock-plus       0.93      0.95      0.94       602
                            adobe       0.95      0.87      0.91      2435
                  aeroflot-online       0.82      0.89      0.86       236
                        afisha-ru       0.75      0.88      0.81       117
                         alfabank       0.97      0.95      0.96      1195
       ali-wangwang-file-transfer       0.75      0.79      0.77        97
                           alipay       0.73      0.81      0.77        69
                       amd-online       0.83      0.80      0.82       111
                           andata       0.68      0.87      0.76        30
                          any-run       0.84      0.91      0.87       222
                            anygo       0.97      0.99      0.98      1336
                      appdynamics       0.71      0.74      0.73        27
                  apple-community       0.14      0.40      0.21       417
                       apple-siri       0.24      0.91      0.38        47
                     apple_icloud       0.96      0.94      0.95      2385
                       apple_push       0.98      0.90      0.94      2445
                        apteka-ru       0.51      0.70      0.59        27
                            avito       0.93      0.89      0.91      2262
                            azure       0.80      0.89      0.84       684
                         banki-ru       0.49      0.64      0.56        39
                   beeline-online       0.77      0.87      0.82       270
                             bing       0.93      0.92      0.92      2412
                            bitly       0.94      0.96      0.95      1169
                     blog-posting       0.51      0.65      0.57       153
                        braintree       0.21      0.55      0.30        31
                          bugsnag       0.77      0.77      0.77        30
                            bybit       0.65      0.91      0.76        77
                  ca-technologies       0.90      0.90      0.90       253
                   cackle-widgets       0.42      0.71      0.53        34
                      cardsmobile       0.35      0.88      0.50        80
                             cdek       0.38      0.66      0.48        88
                           chatra       0.82      0.79      0.81        29
check-point-software-technologies       0.78      0.75      0.77        68
                             cian       0.88      0.95      0.91       431
                         citilink       0.58      0.79      0.67        52
                   cloudflare.dns       0.90      0.96      0.93       235
                             coub       0.31      0.68      0.43        28
                         crazyegg       0.31      0.69      0.43        52
                         createjs       0.99      0.99      0.99       133
                       criteo-ads       0.83      0.92      0.87       394
                    ctc-tv-online       0.37      0.86      0.52        28
                           cursor       0.95      0.95      0.95      1147
                         dashlane       0.70      0.93      0.80        28
                          datadog       0.85      0.85      0.85        88
                            deepl       0.90      0.92      0.91       469
                       demandbase       0.48      0.93      0.63        28
                          directv       0.69      0.69      0.69        48
                           disqus       0.56      0.75      0.64        53
                         dns-shop       0.78      0.84      0.81       439
                           docker       0.98      0.95      0.96      1261
                         domclick       0.60      0.85      0.70       245
                           dotvpn       0.97      0.97      0.97        86
                          drom-ru       0.36      0.58      0.44       130
                             dzen       0.99      0.97      0.98      2419
                             eBay       0.37      0.60      0.45        42
                          ea-fifa       0.83      0.97      0.90        31
                   eapteka-online       0.54      0.83      0.66        93
                          elastic       0.93      0.90      0.92       325
                            emias       0.69      0.98      0.81        45
                        epicgames       0.81      0.92      0.86       333
                         evernote       0.57      0.82      0.68        85
                           fastly       0.96      0.94      0.95      1744
                          felo-ai       0.88      0.97      0.93        38
                            figma       0.84      0.89      0.86       885
                        getcourse       0.71      0.81      0.76       129
                         gigacode       0.98      0.98      0.98       491
                         gismeteo       0.75      0.91      0.82        43
                          gitbook       0.35      0.64      0.46        28
                           google       0.90      0.75      0.82      2406
                      google_docs       0.93      0.94      0.94      2404
                     google_drive       0.90      0.89      0.90      1395
                      google_maps       0.34      0.81      0.48       123
                        gosuslugi       0.97      0.97      0.97      1317
                        grammarly       0.77      0.91      0.83       369
                         gravatar       0.75      0.87      0.80       542
                             habr       0.87      0.89      0.88      1135
                      head-hunter       0.97      0.97      0.97      1299
                            holst       0.96      0.94      0.95      1958
                          hubspot       0.45      0.61      0.52        54
                         huntflow       0.94      0.93      0.94      1169
              ibm-kenexa-products       0.68      0.77      0.72        35
                            imgur       0.67      0.82      0.73        44
                         intercom       0.96      0.95      0.95      1282
                        jetbrains       0.94      0.90      0.92      1569
                         jsdelivr       0.82      0.89      0.86       446
                        kaspersky       0.96      0.94      0.95      2451
                           kontur       0.78      0.63      0.70      2400
                           lamoda       0.89      0.95      0.92       495
                         lastpass       0.76      0.94      0.84       116
                    lenovo-online       0.68      0.83      0.75       212
                             lens       0.97      0.90      0.94        40
                          lichess       1.00      0.99      1.00      1288
                           litres       0.74      0.82      0.78       176
                          mail_ru       0.93      0.89      0.91      2409
                        mailchimp       0.34      0.66      0.45        35
                           mapbox       0.54      0.69      0.61        36
                           matlab       0.77      0.88      0.82       145
                        media-net       0.44      0.73      0.55        33
                  mediatek-online       0.85      0.98      0.91        48
                       metatrader       0.54      0.81      0.65        31
                        microsoft       0.67      0.43      0.52      2387
                          mindbox       0.91      0.94      0.93      1224
                             miro       0.92      0.62      0.74      2416
                      miui-online       0.85      0.90      0.88       525
                      moex-online       0.98      1.00      0.99       618
                           mos-ru       0.87      0.89      0.88       729
                          mozilla       0.97      0.95      0.96      2415
                      ms_onedrive       0.97      0.99      0.98       966
                              mts       0.92      0.78      0.84      2310
                      multifactor       0.98      0.97      0.97      1041
                        nbc-video       0.66      0.72      0.69        54
                        net-beans       0.42      0.64      0.51        39
                        new-relic       0.97      0.95      0.96      1636
                           notion       0.67      0.85      0.75       102
                            nuget       0.83      0.94      0.88       236
                           nvidia       0.79      0.91      0.84       390
                       office_365       0.92      0.86      0.89      2436
                          okko-tv       0.44      0.66      0.53        71
                        opendrive       0.34      0.88      0.49        33
                   otpbank-online       0.83      0.80      0.81        74
                     password-box       0.64      0.94      0.76        34
                           pikabu       0.86      0.89      0.88      1067
                        pinterest       0.56      0.71      0.63       377
                          postman       0.66      0.79      0.72       135
                       premier-tv       0.54      0.86      0.67        29
                         profi-ru       0.70      0.90      0.79       144
                           pushed       0.82      0.93      0.87       157
                             pypi       0.92      0.92      0.92       645
                       raiffeisen       0.95      0.97      0.96       651
                          rambler       0.91      0.87      0.89      1411
                     razer-online       0.60      0.84      0.70        25
                    realtimeboard       0.17      0.77      0.28       156
                           reg-ru       0.86      0.88      0.87       224
                           roblox       0.79      0.96      0.87       205
                         ru-store       0.98      0.98      0.98      1736
                          samokat       0.81      0.92      0.86       253
                   samsung-online       0.96      0.97      0.97      1313
                  samsung-updates       0.54      0.86      0.66        70
                      sber_online       0.97      0.94      0.96      2083
                          segment       0.74      0.86      0.80       322
                           sentry       0.88      0.95      0.91       389
                     sharethrough       0.80      0.94      0.86        88
                           shodan       0.96      0.96      0.96       126
                       similarweb       0.84      0.91      0.87        64
                            slack       0.87      0.93      0.89       188
                          smotrim       0.80      0.88      0.84       283
                        snapcraft       0.66      0.75      0.70       176
                            split       0.87      0.87      0.87      1480
                    stackoverflow       0.82      0.81      0.81       100
                            start       0.67      0.85      0.75        54
                           stepik       0.26      0.76      0.38        55
                             sway       0.38      0.43      0.40      1024
                           t-bank       0.89      0.63      0.74      2429
                           taobao       0.76      0.90      0.83        82
                      tech-target       0.59      0.89      0.71        27
                     tembo-social       0.66      0.67      0.66       121
                         teradata       0.62      0.87      0.72       214
              the-weather-channel       0.93      0.97      0.95       429
                            tilda       0.76      0.84      0.80       641
                          tinkoff       0.32      0.70      0.44       398
                      tns-counter       0.97      0.97      0.97      2013
                         to-doist       0.39      0.86      0.53        42
                     trading-view       0.78      0.81      0.79       615
                 transneft-online       0.62      1.00      0.77        33
                           trello       0.63      0.90      0.74       112
                             tria       1.00      0.99      1.00      2443
                         tripster       0.22      0.48      0.30        31
                          tv4play       0.88      0.94      0.91       392
                       tweet-feed       0.94      0.97      0.96        33
                           twinby       0.82      1.00      0.90       122
                           ubuntu       0.48      0.56      0.52       151
                          unity3d       0.88      0.90      0.89       895
                           upbase       0.95      0.97      0.96       617
                        upto-like       0.78      0.84      0.81        25
                             vigo       0.95      0.98      0.97       796
                            vimeo       0.92      0.91      0.92       341
                       virustotal       0.63      0.88      0.73       105
                    visual-studio       0.89      0.88      0.89      1231
                        vkontakte       0.96      0.91      0.94      2421
                              vtb       0.75      0.85      0.80       378
                       wikiportal       0.99      0.98      0.99      1723
    windows-defender-atp-endpoint       0.06      0.42      0.10        99
       windows-push-notifications       0.82      0.98      0.89        82
                   windows_update       0.52      0.68      0.59        34
                      wondershare       0.76      0.93      0.84        41
                       workingvpn       0.96      0.99      0.98       222
                               x5       0.80      0.92      0.86        49
                        xbox-live       0.51      0.86      0.64        43
                    xiaomi-online       0.83      0.87      0.85       783
                            yahoo       0.81      0.83      0.82       572
                      yandex_disk       0.90      0.95      0.92       896
                      yandex_mail       0.98      0.98      0.98      2432
                      yandex_maps       0.97      0.96      0.97      2449
                     yandex_music       0.98      0.99      0.98      1569
                     yandex_video       0.86      0.91      0.88      2384
                           yonote       0.81      0.91      0.86       308
                             zoom       0.90      0.88      0.89      1302
                             zvuk       0.65      0.86      0.74       175

                         accuracy                           0.88    200000
                        macro avg       0.76      0.85      0.79    200000
                     weighted avg       0.89      0.88      0.88    200000